# Generated by Django 3.2.8 on 2021-10-26 00:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('P', 'Pizza'), ('H', 'Hamburguer'), ('D', 'Doce')], default='P', max_length=10)),
                ('imagem', models.ImageField(blank=True, upload_to='lanches/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=30)),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 10, 26, 0, 54, 42, 3967, tzinfo=utc))),
                ('quantidade', models.IntegerField(default=1)),
                ('fk_Lanche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.lanche')),
            ],
        ),
    ]
